In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [2]:
df = pd.read_csv('Datasets Energia/Energy data 1990 - 2020.csv', encoding='latin1')
df.head()

,ï»¿country,Year,Region,CO2 emissions from fuel combustion (MtCO2),Average CO2 emission factor (tCO2/toe),CO2 intensity at constant purchasing power parities (kCO2/$15p),Total energy production (Mtoe),Total energy consumption (Mtoe),Share of renewables in electricity production (%),Share of electricity in total final energy consumption (%),...,Refined oil products production (Mt),Natural gas production (bcm),Natural gas domestic consumption (bcm),Energy intensity of GDP at constant purchasing power parities (koe/$15p),Electricity production (TWh),Electricity domestic consumption (TWh),Coal and lignite domestic consumption (Mt),Share of wind and solar in electricity production (%),Crude oil production (Mt),Coal and lignite production (Mt)
0,Algeria,1990,Arab States,52.981921,2.387855,0.228889,100.112749,22.188078,0.782972,8.376592,...,25.395,45.68403547,14.301991,0.095856,17.242,13.693,0.94,0,57.850,0
1,Algeria,1991,Arab States,57.149971,2.435026,0.249895,102.586171,23.469959,1.580793,7.994748,...,25.435,49.53198889,15.312995,0.102625,18.535,14.058,1.171,0,57.076,0
2,Algeria,1992,Arab States,57.262430,2.383517,0.245959,104.205908,24.024343,1.022926,8.490068,...,25.459,51.67001137,15.727010,0.103192,19.454,15.130,1.056,0,56.904,0
3,Algeria,1993,Arab States,59.198702,2.455335,0.259730,104.928745,24.110238,1.709195,8.291029,...,25.463,52.38599054,16.596984,0.105782,20.653,15.144,1.015,0,56.995,0
4,Algeria,1994,Arab States,56.347927,2.424649,0.249468,100.612596,23.239627,0.783869,9.170605,...,23.971,48.20601995,16.117004,0.102888,21.177,15.545,0.943,0,56.312,0

In [3]:
df.dtypes

ï»¿country                                                                   object
Year                                                                          int64
Region                                                                       object
CO2 emissions from fuel combustion (MtCO2)                                  float64
Average CO2 emission factor (tCO2/toe)                                      float64
CO2 intensity at constant purchasing power parities (kCO2/$15p)             float64
Total energy production (Mtoe)                                              float64
Total energy consumption (Mtoe)                                             float64
Share of renewables in electricity production (%)                           float64
Share of electricity in total final energy consumption (%)                  float64
Oil products domestic consumption (Mt)                                      float64
Refined oil products production (Mt)                                        float64
Natural gas production (bcm)                                                 object
Natural gas domestic consumption (bcm)                                      float64
Energy intensity of GDP at constant purchasing power parities (koe/$15p)    float64
Electricity production (TWh)                                                float64
Electricity domestic consumption (TWh)                                      float64
Coal and lignite domestic consumption (Mt)                                   object
Share of wind and solar in electricity production (%)                        object
Crude oil production (Mt)                                                   float64
Coal and lignite production (Mt)                                             object
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1364 entries, 0 to 1363
Data columns (total 21 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   ï»¿country                                                                1364 non-null   object
 1   Year                                                                      1364 non-null   int64
 2   Region                                                                    1364 non-null   object
 3   CO2 emissions from fuel combustion (MtCO2)                                1364 non-null   float64
 4   Average CO2 emission factor (tCO2/toe)                                    1364 non-null   float64
 5   CO2 intensity at constant purchasing power parities (kCO2/$15p)           1364 non-null   float64
 6   Total energy production (Mtoe)                                            1364 non-null   float64
 7   Total energy consumption (Mtoe)                                           1364 non-null   float64
 8   Share of renewables in electricity production (%)                         1364 non-null   float64
 9   Share of electricity in total final energy consumption (%)                1364 non-null   float64
 10  Oil products domestic consumption (Mt)                                    1364 non-null   float64
 11  Refined oil products production (Mt)                                      1364 non-null   float64
 12  Natural gas production (bcm)                                              1364 non-null   object
 13  Natural gas domestic consumption (bcm)                                    1364 non-null   float64
 14  Energy intensity of GDP at constant purchasing power parities (koe/$15p)  1364 non-null   float64
 15  Electricity production (TWh)                                              1364 non-null   float64
 16  Electricity domestic consumption (TWh)                                    1364 non-null   float64
 17  Coal and lignite domestic consumption (Mt)                                1364 non-null   object
 18  Share of wind and solar in electricity production (%)                     1364 non-null   object
 19  Crude oil production (Mt)                                                 1364 non-null   float64
 20  Coal and lignite production (Mt)                                          1364 non-null   object
dtypes: float64(14), int64(1), object(6)
memory usage: 223.9+ KB

In [5]:
df.columns

Index(['ï»¿country', 'Year', 'Region',
       'CO2 emissions from fuel combustion (MtCO2)',
       'Average CO2 emission factor (tCO2/toe)',
       'CO2 intensity at constant purchasing power parities (kCO2/$15p)',
       'Total energy production (Mtoe)', 'Total energy consumption (Mtoe)',
       'Share of renewables in electricity production (%)',
       'Share of electricity in total final energy consumption (%)',
       'Oil products domestic consumption (Mt)',
       'Refined oil products production (Mt)', 'Natural gas production (bcm)',
       'Natural gas domestic consumption (bcm)',
       'Energy intensity of GDP at constant purchasing power parities (koe/$15p)',
       'Electricity production (TWh)',
       'Electricity domestic consumption (TWh)',
       'Coal and lignite domestic consumption (Mt)',
       'Share of wind and solar in electricity production (%)',
       'Crude oil production (Mt)', 'Coal and lignite production (Mt)'],
      dtype='object')

In [7]:
df.groupby([ 'Region', 'ï»¿country']).aggregate('mean', 'min', 'max')

                                            Year  \
Region              ï»¿country
Africa              Nigeria               2005.0
                    South Africa          2005.0
Arab States         Algeria               2005.0
Asia & Pacific      Australia             2005.0
                    China                 2005.0
                    India                 2005.0
                    Indonesia             2005.0
                    Japan                 2005.0
                    Kazakhstan            2005.0
                    Malaysia              2005.0
                    New Zealand           2005.0
                    South Korea           2005.0
                    Taiwan                2005.0
                    Thailand              2005.0
                    Uzbekistan            2005.0
Europe              Belgium               2005.0
                    Czechia               2005.0
                    France                2005.0
                    Germany               2005.0
                    Italy                 2005.0
                    Netherlands           2005.0
                    Norway                2005.0
                    Poland                2005.0
                    Portugal              2005.0
                    Romania               2005.0
                    Russia                2005.0
                    Spain                 2005.0
                    Sweden                2005.0
                    Turkey                2005.0
                    Ukraine               2005.0
                    United Kingdom        2005.0
Middle east         Egypt                 2005.0
                    Iran                  2005.0
                    Kuwait                2005.0
                    Saudi Arabia          2005.0
                    United Arab Emirates  2005.0
North America       Canada                2005.0
                    United States         2005.0
South/Latin America Argentina             2005.0
                    Brazil                2005.0
                    Chile                 2005.0
                    Colombia              2005.0
                    Mexico                2005.0
                    Venezuela             2005.0

                                          CO2 emissions from fuel combustion (MtCO2)  \
Region              ï»¿country
Africa              Nigeria                                                57.810707
                    South Africa                                          359.419868
Arab States         Algeria                                                89.154083
Asia & Pacific      Australia                                             348.188850
                    China                                                5724.498079
                    India                                                1292.659050
                    Indonesia                                             347.153265
                    Japan                                                1121.973933
                    Kazakhstan                                            187.206592
                    Malaysia                                              154.972152
                    New Zealand                                            29.460870
                    South Korea                                           490.801586
                    Taiwan                                                220.033472
                    Thailand                                              194.671301
                    Uzbekistan                                            112.662909
Europe              Belgium                                               107.619218
                    Czechia                                               116.201310
                    France                                                359.243749
                    Germany                                               809.060833
                    Italy                                                 394.505061
                    Netherlands                                           177.581045
                    Norway                                                 35.744378
                    Poland                                                315.759226
                    Portugal                                               50.704906
                    Romania                                                93.427082
                    Russia                                               1641.490007
                    Spain                                                 262.047717
                    Sweden                                                 48.127162
                    Turkey                                                241.956261
                    Ukraine                                               323.624297
                    United Kingdom                                        487.451715
Middle east         Egypt                                                 148.083596
                    Iran                                                  418.597617
                    Kuwait                                                 60.398898
                    Saudi Arabia                                          341.394795
                    United Arab Emirates                                  122.683244
North America       Canada                                                524.100556
                    United States                                        5296.976691
South/Latin America Argentina                                             142.759006
                    Brazil                                                329.998674
                    Chile                                                  60.590589
                    Colombia                                               59.881795
                    Mexico                                                390.263902
                    Venezuela                                             125.567801

                                          Average CO2 emission factor (tCO2/toe)  \
Region              ï»¿country
Africa              Nigeria                                             0.520252
                    South Africa                                        3.020495
Arab States         Algeria                                             2.398145
Asia & Pacific      Australia                                           3.091341
                    China                                               2.930238
                    India                                               2.151622
                    Indonesia                                           1.957178
                    Japan                                               2.364443
                    Kazakhstan                                          3.149056
                    Malaysia                                            2.488923
                    New Zealand                                         1.677769
                    South Korea                                         2.346359
                    Taiwan                                              2.466459
                    Thailand                                            2.062731
                    Uzbekistan                                          2.408826
Europe              Belgium                                             1.959096
                    Czechia                                             2.679851
                    France                                              1.431562
                    Germany                                             1.909405
                    Italy                                               2.418486
                    Netherlands                                         2.373681
                    Norway                                              1.326625
                    Poland                                              3.241838
                    Portugal                                            2.281785
                    Romania                                             2.360190
                    Russia                                              2.374804
                    Spain                                               2.220274
                    Sweden                                              0.976798
                    Turkey                                              2.614162
                    Ukraine                                             2.276083
                    United Kingdom                                      2.373575
Middle east         Egypt                                               2.414095
                    Iran                                                2.505597
                    Kuwait                                              2.600171
                    Saudi Arabia                                        2.461965
                    United Arab Emirates                                2.508959
North America       Canada                                              1.322882
                    United States                                       2.444130
South/Latin America Argentina                                           2.155463
                    Brazil                                              1.474142
                    Chile                                               2.155287
                    Colombia                                            1.962837
                    Mexico                                              2.378451
                    Venezuela                                           2.259822

                                          CO2 intensity at constant purchasing power parities (kCO2/$15p)  \
Region              ï»¿country
Africa              Nigeria                                                        0.100884
                    South Africa                                                   0.676324
Arab States         Algeria                                                        0.248931
Asia & Pacific      Australia                                                      0.430402
                    China                                                          0.747406
                    India                                                          0.310723
                    Indonesia                                                      0.197814
                    Japan                                                          0.237804
                    Kazakhstan                                                     0.729902
                    Malaysia                                                       0.310400
                    New Zealand                                                    0.225137
                    South Korea                                                    0.398754
                    Taiwan                                                         0.605494
                    Thailand                                                       0.244829
                    Uzbekistan                                                     1.178171
Europe              Belgium                                                        0.250740
                    Czechia                                                        0.431671
                    France                                                         0.154008
                    Germany                                                        0.188072
                    Italy                                                          0.179294
                    Netherlands                                                    0.246348
                    Norway                                                         0.138607
                    Poland                                                         0.488309
                    Portugal                                                       0.174607
                    Romania                                                        0.312771
                    Russia                                                         0.617291
                    Spain                                                          0.187644
                    Sweden                                                         0.133422
                    Turkey                                                         0.187604
                    Ukraine                                                        0.729121
                    United Kingdom                                                 0.222795
Middle east         Egypt                                                          0.198887
                    Iran                                                           0.475411
                    Kuwait                                                         0.457842
                    Saudi Arabia                                                   0.303317
                    United Arab Emirates                                           0.295657
North America       Canada                                                         0.286807
                    United States                                                  0.371559
South/Latin America Argentina                                                      0.217101
                    Brazil                                                         0.139537
                    Chile                                                          0.216841
                    Colombia                                                       0.134986
                    Mexico                                                         0.220113
                    Venezuela                                                      0.324751

                                          Total energy production (Mtoe)  \
Region              ï»¿country
Africa              Nigeria                                   215.768727
                    South Africa                              146.583149
Arab States         Algeria                                   138.888388
Asia & Pacific      Australia                                 279.053354
                    China                                    1714.563657
                    India                                     423.828369
                    Indonesia                                 309.816080
                    Japan                                      79.239063
                    Kazakhstan                                119.075757
                    Malaysia                                   81.489713
                    New Zealand                                14.675231
                    South Korea                                42.389415
                    Taiwan                                     11.697957
                    Thailand                                   54.631283
                    Uzbekistan                                 52.515691
Europe              Belgium                                    13.628168
                    Czechia                                    32.100358
                    France                                    130.804112
                    Germany                                   134.479452
                    Italy                                      31.394149
                    Netherlands                                59.788116
                    Norway                                    201.422433
                    Poland                                     79.253382
                    Portugal                                    4.474088
                    Romania                                    28.953570
                    Russia                                   1192.679967
                    Spain                                      32.509614
                    Sweden                                     32.900214
                    Turkey                                     29.288113
                    Ukraine                                    80.864790
                    United Kingdom                            191.874280
Middle east         Egypt                                      70.942414
                    Iran                                      292.044638
                    Kuwait                                    129.029263
                    Saudi Arabia                              535.945721
                    United Arab Emirates                      175.555349
North America       Canada                                    403.149425
                    United States                            1773.883072
South/Latin America Argentina                                  73.851212
                    Brazil                                    197.908739
                    Chile                                      10.055389
                    Colombia                                   87.693069
                    Mexico                                    214.545808
                    Venezuela                                 187.149403

                                          Total energy consumption (Mtoe)  \
Region              ï»¿country
Africa              Nigeria                                    108.966260
                    South Africa                               118.164616
Arab States         Algeria                                     37.304646
Asia & Pacific      Australia                                  112.624788
                    China                                     1923.259065
                    India                                      579.979809
                    Indonesia                                  171.707898
                    Japan                                      476.681403
                    Kazakhstan                                  59.780130
                    Malaysia                                    61.317567
                    New Zealand                                 17.610403
                    South Korea                                212.370130
                    Taiwan                                      89.016066
                    Thailand                                    95.639456
                    Uzbekistan                                  46.803671
Europe              Belgium                                     55.012831
                    Czechia                                     43.335975
                    France                                     251.178593
                    Germany                                    327.924445
                    Italy                                      162.871426
                    Netherlands                                 74.852016
                    Norway                                      27.039320
                    Poland                                      97.445448
                    Portugal                                    22.239957
                    Romania                                     39.134525
                    Russia                                     691.661445
                    Spain                                      117.913861
                    Sweden                                      49.216149
                    Turkey                                      92.634794
                    Ukraine                                    139.047934
                    United Kingdom                             204.316282
Middle east         Egypt                                       60.926430
                    Iran                                       169.032722
                    Kuwait                                      23.088728
                    Saudi Arabia                               138.349530